/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StaffResetsRouteImport } from './routes/staff.resets'
import { Route as StaffRegistrationsRouteImport } from './routes/staff.registrations'
import { Route as StaffOrdersRouteImport } from './routes/staff.orders'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffCustomersRouteImport } from './routes/staff.customers'
import { Route as StaffActivityRouteImport } from './routes/staff.activity'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as PoliciesReturnsRouteImport } from './routes/policies.returns'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as BrandsIdRouteImport } from './routes/brands.$id'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const StaffResetsRoute = StaffResetsRouteImport.update({
  id: '/resets',
  path: '/resets',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRegistrationsRoute = StaffRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffActivityRoute = StaffActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StaffRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReturnsRoute = PoliciesReturnsRouteImport.update({
  id: '/policies/returns',
  path: '/policies/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIdRoute = BrandsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrandsRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/support': typeof SupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/brands/$id': typeof BrandsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$id': typeof ProductsIdRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/resets': typeof StaffResetsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/brands/$id': typeof BrandsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$id': typeof ProductsIdRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/resets': typeof StaffResetsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/support': typeof SupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/brands/$id': typeof BrandsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$id': typeof ProductsIdRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/resets': typeof StaffResetsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/notifications'
    | '/offers'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/staff'
    | '/support'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/inventory'
    | '/admin/orders'
    | '/brands/$id'
    | '/orders/$id'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/products/$id'
    | '/staff/activity'
    | '/staff/customers'
    | '/staff/notifications'
    | '/staff/orders'
    | '/staff/registrations'
    | '/staff/resets'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/notifications'
    | '/offers'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/support'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/inventory'
    | '/admin/orders'
    | '/brands/$id'
    | '/orders/$id'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/products/$id'
    | '/staff/activity'
    | '/staff/customers'
    | '/staff/notifications'
    | '/staff/orders'
    | '/staff/registrations'
    | '/staff/resets'
    | '/account'
    | '/admin'
    | '/orders'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/notifications'
    | '/offers'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/staff'
    | '/support'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/inventory'
    | '/admin/orders'
    | '/brands/$id'
    | '/orders/$id'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/terms'
    | '/products/$id'
    | '/staff/activity'
    | '/staff/customers'
    | '/staff/notifications'
    | '/staff/orders'
    | '/staff/registrations'
    | '/staff/resets'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRouteWithChildren
  SupportRoute: typeof SupportRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesReturnsRoute: typeof PoliciesReturnsRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/staff/resets': {
      id: '/staff/resets'
      path: '/resets'
      fullPath: '/staff/resets'
      preLoaderRoute: typeof StaffResetsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/registrations': {
      id: '/staff/registrations'
      path: '/registrations'
      fullPath: '/staff/registrations'
      preLoaderRoute: typeof StaffRegistrationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/activity': {
      id: '/staff/activity'
      path: '/activity'
      fullPath: '/staff/activity'
      preLoaderRoute: typeof StaffActivityRouteImport
      parentRoute: typeof StaffRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/returns': {
      id: '/policies/returns'
      path: '/policies/returns'
      fullPath: '/policies/returns'
      preLoaderRoute: typeof PoliciesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$id': {
      id: '/brands/$id'
      path: '/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof BrandsIdRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BrandsRouteChildren {
  BrandsIdRoute: typeof BrandsIdRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsIdRoute: BrandsIdRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface StaffRouteChildren {
  StaffActivityRoute: typeof StaffActivityRoute
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffRegistrationsRoute: typeof StaffRegistrationsRoute
  StaffResetsRoute: typeof StaffResetsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffActivityRoute: StaffActivityRoute,
  StaffCustomersRoute: StaffCustomersRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffRegistrationsRoute: StaffRegistrationsRoute,
  StaffResetsRoute: StaffResetsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRouteWithChildren,
  SupportRoute: SupportRoute,
  OrdersIdRoute: OrdersIdRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesReturnsRoute: PoliciesReturnsRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
